name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  ci-build-and-push:
    name: CI - Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          cd MERN-Stack-Todo-List-App/backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-todo-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-todo-backend:latest

      - name: Build and Push Frontend Image
        run: |
          cd MERN-Stack-Todo-List-App/frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-todo-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-todo-frontend:latest

  cd-deploy:
    name: CD - Deploy to Kubernetes
    needs: ci-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/mongo-deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/mongo-service.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/backend-deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/backend-service.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/frontend-deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f MERN-Stack-Todo-List-App/k8s/frontend-service.yaml
